### PR TITLE
Milestone5: UI

### PR DESCRIPTION
**Pull request by dev1980**
-Implement style to the Components.

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi Team :clap: 

### Awesome job so far!! :+1: 

You have done the basic, we just need to little more styling 🙏 so that your design can look almost the same as the project spec given:
But please Guys, we have strict guidelines as well to follow and one of the requirements is seeing into it that students replicated requirements.

If many students do this, we'll gradually shift away from the requirement from team to team.

Your design is very good, just not requirement-compliant, please try to adhere.THANKS
That's just why you don't get a thumbs up now.......

image

image


Let's work on the following:
1. The header (Use similar font and color and add the text `book` and `category`)
2. The `book `form` (use similar color and little spacing in between input box) 
3. Kindly working on responsiveness, that's is; mobile view; category dropdown menu seems disappeared.
image


**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

**Best,**

**Oluwaseun Bello**

**Comment by fegzycole** [comment]
Hello and good morning @bellom 

Thank you for your speedy review. However, I have some issues with your code review and I have indicated them below:

- You complained about the font family we used, if you look at the public/index.html file, you will see that we used the montserrat family as was indicated on the zeplin spec.

-  We saw no need to add the Book section in the header since we did not implement that functionality

-  From the project specifications, we were made to know that there are features of the design that can be skipped since they have not been implemented, example of which include; **Comment**, **Edit** and the **Progress Report**

- There is no requirement for us to build a responsive application

- We will however work on the color and fix the header to display the **Categories** and also add ample spacing among the textbox, select box and submit button.

Best Regards

**Comment by bellom** [comment]
@fegzycole, 
Well done guys I don't really mean to keep you waiting on your last project, having put energy and time in the program, everyone want to finish the project and move to the next one but sometimes we just need to work on some little correction to show mastery of the skills before moving on.

Sorry my bad, I shouldn't include `font` 🙏 .
And for including the text `book` I'm aware you didn't include the functionality, just to make the UI look the same with the given project spec, ok?

And for mobile view; yes, you're right nothing like that, but working on an advanced project like this, responsiveness is what a developer can work on without being necessarily listed in the requirements, as you know this project will be added to your portfolio.
Sorry once again, I should also tag this as **[Optional]**

The below screenshot shows that you're right and also shows that you should work on the project to the extent of showing it off to a client. 😉 
image
_That's it! Your application is fully functional and ready to be handed over to the client. Great work_

https://github.com/microverseinc/project-redux-bookstore/blob/master/milestones/MILESTONE_5.md

**Comment by fegzycole** [comment]
Thank you for the clarification and your time @bellom, we have made the necessary adjustments and will submit for another review now.

**Review by bellom — APPROVED** [review]
## Hi Team :clap: 

### Wow! You made all the changes even the mobile responsiveness, what a great guy you both are 👍 
**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck with your capstone project :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
